### ISSUE TITLE
Components {tag: "placeholder"} when pendingRequests > 0 is problematic when forcing synchronous redraw

### ISSUE THREAD

**Issue by tobscure** [lhorie/mithril.js#603]
```javascript
var FooPage = {
  view: function(ctrl) {
    return m('div', [
      m('button', {onclick: function() {
        ctrl.bar = true;
        m.redraw(true);
        document.getElementById('bar').style.background = 'red';
      }}, 'click me'),
      ctrl.bar ? m.component(BarComponent) : ''
    ]);
  }
};
var BarComponent = {
  view: function() {
    return m('div#bar', 'I should be red');
  }
};
m.mount(document.body, FooPage);
```

The autoredraw mechanism is calling m.startComputation(), so pendingRequests == 1 when m.redraw(true) is called. Then on line 248 the BarComponent ends up being rendered as {tag: "placeholder"} so its DOM cannot be interacted with until after the autoredraw calls m.endComputation().

What's the reasoning behind the {tag: "placeholder"} thing?

**Comment by barneycarroll** [comment]
Slight tangent — should we regard `placeholder` as a standard dummy element for the purposes of advanced usage that may require, well, placeholders?

**Comment by lhorie** [comment]
It's intended to be a placeholder for asynchronously rendered components, since it's generally expected that a view function will only run after its respective controller

**Comment by lhorie** [comment]
This is fixed in origin/next

**Comment by lhorie** [comment]
@barneycarroll to answer your question: it's [documented](http://lhorie.github.io/mithril/mithril.component.html#nested-asynchronous-components), so yes

**Comment by tobscure** [comment]
@lhorie where's the commit? Not seeing it yet

**Comment by tobscure** [comment]
@lhorie sorry to bug, still having this issue in the latest origin/next.

**Comment by lhorie** [comment]
@tobscure oops sorry, the push had failed.

**Comment by tobscure** [comment]
@lhorie Thanks!
